version: "3.5"
services:

  mysql:
    image: mysql:5.7              # 如果遇到不正确的数据库配置，或无法连接到数据库PDOException: SQLSTATE[HY000] [1045] 用户'yourls'@'yourls_service.yourls_default'的访问被拒绝（使用密码：是）   可以把5.7.22 改为 5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Juejin10241024
      - MYSQL_DATABASE=yourls
      - MYSQL_USER=juejin
      - MYSQL_PASSWORD=Juejin10241024
    volumes:
      - ./mysql/db/:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d
    restart: always
    container_name: mysql
  
  yourls:
    image: yourls
    restart: always
    ports:
      - "8200:80"
    environment:
      YOURLS_DB_HOST: mysql
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: 123456
      YOURLS_DB_NAME: yourls
      YOURLS_USER: admin      # 自己起一个名字
      YOURLS_PASS: 123456      # 自己换一个登陆密码
      YOURLS_SITE: http://dl.ylimhs.cn  # 换成你自己的域名
      YOURLS_HOURS_OFFSET: 8
      YOURLS_LANG: zh_CN
    volumes:
      - ./yourls_data/:/var/www/html   
    container_name: yourls_service
    links:
      - mysql:mysql
  

